#!/usr/bin/php

<?php

if (php_sapi_name() !== 'cli') {
    exit;
}

require __DIR__ . '/vendor/autoload.php';

use App\App;

$config = require __DIR__ . '/config/config.php';

$app = new App($config);
$app->bootstrap();
$app->run($argv);
